# Generated by Django 2.2.4 on 2019-10-06 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20191006_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 10, 48, 48, 81887, tzinfo=utc)),
        ),
    ]
