# Generated by Django 2.2.4 on 2019-10-08 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20191006_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 17, 34, 17, 76352, tzinfo=utc)),
        ),
    ]
