# Generated by Django 2.2.4 on 2019-10-17 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20191008_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 8, 19, 42, 618527, tzinfo=utc)),
        ),
    ]
